quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db-k
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
# 4. Connection pool settings (optional but recommended)
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10

# Hibernate ORM settings
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=quarkus-avancado

quarkus.log.category."io.quarkus.cache".level=DEBUG

mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092

# Outgoing channel -> topic estoque-baixo
mp.messaging.outgoing.estoque-baixo-out.connector=smallrye-kafka
mp.messaging.outgoing.estoque-baixo-out.topic=estoque-baixo
mp.messaging.outgoing.estoque-baixo-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Incoming channel <- topic estoque-baixo
mp.messaging.incoming.estoque-baixo-in.connector=smallrye-kafka
mp.messaging.incoming.estoque-baixo-in.topic=estoque-baixo
mp.messaging.incoming.estoque-baixo-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.estoque-baixo-in.group.id=estoque-alerta-group